services:
  - type: web
    name: luminous-candles-api
    env: python
    region: oregon  # or choose closest region: frankfurt, singapore, etc.
    plan: free       # or "starter" / "standard" / "pro" depending on your plan

    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt

    startCommand: |
      uvicorn main:app --host 0.0.0.0 --port 10000

    envVars:
      - key: ENV
        value: production
      - key: STRIPE_SECRET_KEY_TEST
        sync: false
      - key: STRIPE_SECRET_KEY_LIVE
        sync: false
      - key: SENDGRID_API_KEY
        sync: false
      - key: FROM_EMAIL
        sync: false
      - key: ADMIN_EMAIL
        sync: false
